# Generated by Django 3.2.7 on 2021-10-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Md',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engword', models.CharField(max_length=20)),
                ('rusword', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True, db_index=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Словарь',
                'ordering': ['-published'],
            },
        ),
    ]
